### ISSUE TITLE
Drop the levels/versioning

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#107]
For when we move to Web Apps WG, we should consider dropping the spec Levels... instead, we should make pull requests for the level 2 features and try to get other browser vendors behind it. It seems like we (Mozilla) might be willing to support `.canShare()` and sharing `File`s out of the box, so that would give us two implementations (bar review of the actual features, that we are yet to do)... we would then need to sell the Safari folks on supporting those features 🤞.

**Comment by marcoscaceres** [comment]
@grorg or @hober, who would be the right person to loop in on Web Share from WebKit?

**Comment by marcoscaceres** [comment]
Thanks @hober @hortont424. Would really like your input about the above: the non-standard features that Chrome is currently shipping in their "v2" of Web Share. 

On the Mozilla side, we are not ready to commit to the features that are in V2 until we've done a more thorough security and privacy evaluation of what's being added - sharing files is pretty scary, so we need a good security model for that. 

Thus, I'd personally like for V2 to become pull requests rather than being a separate document. Otherwise, it risks sending confusing messages to developers (i.e., that there is consensus on the v2 feature set, when right now there is none). That's not to say there is anything wrong with the V2 stuff - sharing files is obviously really important as a use case... but from the Mozilla perspective, would rather go into this with some WebKit support too.

**Comment by hober** [comment]
I've talked about this with a few colleagues and I think we're generally supportive of adding file sharing. Like @marcoscaceres, I'd prefer a level-less approach where new features come in as PRs on one document.

**Comment by marcoscaceres** [comment]
@mgiuca, wdyt? The addition of file(s) support leads to the discussion around `canShare()` as a feature detection mechanism #108. We can probably do them as separate PRs.

**Comment by mgiuca** [comment]
Yep, we're happy to piece-by-piece merge V2 into V1 spec. Should we wait for a second implementation on each piece before merging?

**Comment by marcoscaceres** [comment]
I can commit to prototyping both methods (and hopefully land them proper) in Gecko over the next few months. We might be able to land the changes in the spec before we ship, but just want to make sure we have some cross-engine implementation experience.

**Comment by inexorabletash** [comment]
Can we at the very least update the URL show on the project page from 
https://w3c.github.io/web-share/ to https://w3c.github.io/web-share/level-2/

![image](https://user-images.githubusercontent.com/771547/80741561-adae5180-8ace-11ea-90d8-3c5c8154fcec.png)

**Comment by mgiuca** [comment]
We probably shouldn't, since the way we're looking at these two "levels" (probably the wrong word now) is that L1 is the "official" W3C spec that's been agreed upon by multiple parties, while L2 contains features that have not been approved. It's more like a WICG, even though it isn't in a WICG repo. Marcos has said he wants to add more "unofficial" text to the L2 spec, similar to a WICG.

Possibly it should actually go to a WICG repo, but I don't want the overhead of maintaining two repos for one API. I am happy if we want to use the WICG incubator style settings on the L2 document, so that it displays "Unofficial Draft" at the top.

**Comment by marcoscaceres** [comment]
We are discussing what to do more generally in https://github.com/WICG/admin/issues/102 ... it's complicated, but we are open to proposals.

**Comment by othermaciej** [comment]
>  It's more like a WICG, even though it isn't in a WICG repo. 

If you're saying it's an incubation and not standards track, then it's wrong for it to be in a Working Group, as Working Groups are not chartered for incubation work; it should actually be in WICG instead. The front matter of the spec claims it's a WICG deliverable, but it's not documented as such in official WICG lists of incubations such as [this](https://docs.google.com/spreadsheets/d/1K2EtkvKXMDk_h2goR34uMIWmw1LfPhIi-QAJHcQBP_4/edit#gid=0) or [this](https://wicg.io). I also could not find signs on https://discourse.wicg.io of Web Share Level 2 being adopted by WICG. I was able to find the adoption for the original Web Share, but that was handed off to Web App sWG. Maybe there are missing records, but the Web Share Level 2 spec should not claim to be a WICG deliverable if it isn't.

Note: this is not a commentary on the features in level 2. I believe WebKit has even [implemented some of them](https://bugs.webkit.org/show_bug.cgi?id=207491), though not yet shipping. And we'd support promoting any features we implement that have multi-engine support to the main spec.

**Comment by marcoscaceres** [comment]
So, the confusion around the L1 and L2 was that they were _both_ WICG documents before we moved everything to the WebAppsWG. The separation was made between L1 and L2 based on L1 features being implemented in both Chrome and Safari... the L2 stuff was just Chrome specific at the time. In https://github.com/w3c/web-share/issues/107 @hober and I requested that the L2 stuff just get moved into L1, and we just drop levels entirely.

**Comment by sulaeman51** [comment]
Kode 740063

Terima kasih atas masukan nya github ..mohon bantuan dan bimbingan nya ..perankat kerja saya rusak terus karena pihak ke 3 ..bekerja di perangkat saya ..

Dan tadi saya di hubungi langsung pihak Alibaba 

Sekarang pihak ke 3 menggunakan Microsoft azuri

izkadelpan@gmail.com
izdelpan@gmail.com
Izkadebrow.wordpres

Mohon bantuan nya github karena saya tidak paham tentang komputer ..apa perlu di remot dari sana 

Terima kasih atas bantuan nya.....

Maaf apa saya salah tempat untuk minta bantuan 
Prihal ini 
I
