### ISSUE TITLE
canShare(data) without filepicker

### ISSUE THREAD

**Issue by 10eputzen** [w3c/web-share#114]
I build a [codePen](https://codepen.io/anon/pen/xvXvPZ?editors=1010) where I was trying out different ways to call `canShare(data)`. 
I only get it working when you select a file from your phone.
Is there a way to share a file e.g. an Mp3 without selecting in manually - so for example a file from a url?
Everytime I try I get:
**NotAllowedError: Permission denied**

**Comment by ewilligers** [comment]
See https://github.com/WICG/web-share/issues/104

You can also create a File using JavaScript - see [test](https://github.com/web-platform-tests/wpt/blob/master/web-share/share-files-manual.html).

**Comment by 10eputzen** [comment]
@ewilligers  It does work on #104, but in my (Angular) [codepen ](https://codepen.io/anon/pen/xvXvPZ) I always get  the following error
**"NotAllowedError: Permission denied".**
Any idea why?
I also tried downloading the file and then write it to a new file but with the same result

**Comment by 10eputzen** [comment]
ok nevermind my codepen has a different problem as well, the error is just the same

**Comment by souvik2701** [comment]
> See #104
> 
> You can also create a File using JavaScript - see [test](https://github.com/web-platform-tests/wpt/blob/master/web-share/share-files-manual.html).

Tried to copy [test](https://github.com/web-platform-tests/wpt/blob/master/web-share/share-files-manual.html) but seem to throw the same "Permission Denied" error
Here's the Pen:
 https://codepen.io/souvik2701/pen/wvwmJLR

**Comment by ewilligers** [comment]
Chrome does not permit `https://i.ibb.co/WVm8gyb/share100.jpg` as a file name - [`share100.jpg`](https://codepen.io/ewilligers/pen/BaBrRKM) works.

**Comment by souvik2701** [comment]
> Chrome does not permit `https://i.ibb.co/WVm8gyb/share100.jpg` as a file name - [`share100.jpg`](https://codepen.io/ewilligers/pen/BaBrRKM) works.

Sorry for the silly question, Is something like `share.php?id=123` permitted? I generate images using PHP script.

**Comment by ewilligers** [comment]
> Is something like `share.php?id=123` permitted? I generate images using PHP script.

You can create a File with such an image as the content: `new File([image], 'share100.jpg', options);`

We don't want WebShare to be a way to deliver malicious executables, so for example Chrome only supports specific file extensions and MIME types (i.e. we use allow lists instead of block lists). The common text, audio, image and video formats on the web are supported.
