### ISSUE TITLE
What should happen is if underlying page navigates?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#120]
What should happen is if underlying page navigates while a share UI is being shown? We could say that the UA SHOULD bring down the share sheet and rejects, if possible.

**Comment by mgiuca** [comment]
Why does it need to do this (or even mention it, though I'd be happy to mention it if it makes you happy)?

As I was saying on #119, I view it as once you've called `share()`, the share is off into the hands of the operating system. There is nothing tying the sharing site to the data, other than the one-way (return) message of whether the share succeeded or not.

I don't think the spec should particularly care whether navigation brings down the share sheet or not. If we have to have an opinion, I think it _shouldn't_ bring down the share sheet (as I said, on Android I don't think we even could do that if we wanted to).

I'd also be happy to say it "MAY" (without having an opinion one way or another), though I guess that could potentially lead to inconsistent behaviour if a site calls `share()` then immediately navigates away; some browsers would flash a picker then close it, while another browser might keep the share picker up.

**Comment by marcoscaceres** [comment]
> As I was saying on #119, I view it as once you've called share(), the share is off into the hands of the operating system. 

This is not the case in every OS. Again, see Safari's Desktop implementation, in which the browser is still in control of the share UI. 

It's more of the site waiting to do work:

```JS
try {
   // Blocked here awaiting... 
   await navigator.share( things );
catch (err) {
   // something didn't go right... let's clean up.
}  finally {
  // do important stuff
}

// other code elsewhere... 
onSomeServerEvent = newURL => {
  navigator.location =  newURL;
}
```

Now, if we note in the spec that it's unreliable (SHOULD or MAY), then that's a good thing. If we can make it more reliable, better.

**Comment by mgiuca** [comment]
If the site navigates away, then you won't be able to run code in either the `catch` or the `finally` before it navigates. So this can't be about allowing cleanup to happen inside the page context.

I think the legitimate concern here is what I said above, that if you navigate away while the user is picking, you may destroy the share sheet on some browsers but not on others. I'm not sure that's a big concern though.

> This is not the case in every OS. Again, see Safari's Desktop implementation, in which the browser is still in control of the share UI.

Sorry, I should have been more clear. It's off into the hands of _something_ outside of the site's control (either the user agent or the operating system). It's invisible to the site other than its success status (but you can't see its success status if you've navigated away, so we don't need to specify what happens).

**Comment by marcoscaceres** [comment]
> I think the legitimate concern here is what I said above, that if you navigate away while the user is picking, you may destroy the share sheet on some browsers but not on others. I'm not sure that's a big concern though.

It's not a big concern. You are correct that once it goes to the OS, the browser may no longer have any control. 

Closing for now and let's see how we go.
