### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/web-share#121]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by mgiuca** [comment]
Hi Leonie,

Unfortunately I will be unable to attend TPAC this year, but here are the answers to those questions:

> What progress has your spec made in the last 12 months?

* Implementation in Safari on iOS and macOS.
* Addition of Level 2 spec that allows sharing of files.
* Implementation of Level 2 in Chrome on Android.
* Migrated from WICG to W3C as an Editor's Draft.

> Is anything blocking your spec from moving to CR?

The Level 1 spec is reasonably mature and has two separate implementations (Chromium and WebKit). It hasn't been through a formal process, having just been migrated to W3C.

> What do you want to achieve for your spec in the next two days (of breakout sessions)?

I won't be able to attend and not sure if anyone will be able to proxy for me.

**Comment by marcoscaceres** [comment]
If there are implementers in the room, it would be good to discuss #107 and the features the proposed additions. 

It might be good to discuss if it's possible to implement on Windows or not... it seems we might be missing some things in the Windows native APIs: it's not possible to detect if the user aborts - this is the same limitation that is on Android, right @mgiuca?  

CC @travisleithead , @aarongustafson from Microsoft. cc @saschanaz,  who has been looking at implementing on Windows via Gecko. A good follow on discussion might be to discuss what we do about bringing over Web Share Target... and if there is much hope in getting OS-level support (and if we need it). 

We need to evaluate the state of tests in WPT, but I imagine it's pretty good.

**Comment by marcoscaceres** [comment]
@saschanaz spotted that [Windows 10 SDK Preview Build 18965 has `ShareCanceled` event](https://blogs.windows.com/windowsdeveloper/2019/08/27/windows-10-sdk-preview-build-18965-available-now/#xvJMbuCiEXe5ByvR.97):

```C#
namespace Windows.ApplicationModel.DataTransfer {
  public sealed class DataPackage {
    event TypedEventHandler<DataPackage, object> ShareCanceled;
  }
}
```

**Comment by marcoscaceres** [comment]
Closing as answered...
