### ISSUE TITLE
Preparations for First Public Working Draft

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#129]
Given the good state of the spec, it would be good for us to prepare the document for a First Public Working Draft. In order us to do that, as per the [W3C Process](https://www.w3.org/2019/Process-20190301/#first-wd), we:

- [x] [must record the group's decision to request advancement](https://lists.w3.org/Archives/Public/public-webapps/2019OctDec/0011.html).
- [x] [fill out issue](http://github.com/w3c/transitions) 
- [x] must provide public documentation of any Formal Objections - none.
- [x] should provide public documentation of changes that are not substantive - provided via github's commit history. 
- [x] should report any changes in dependencies with other groups - none.
- [X] should provide information about implementations known to the Working Group - done.
- [ ] initiate wide review - will do that after it gets published.  

@mgiuca, if you agree, I'll send out a Call for Consensus to publish to the WG, which will address the first requirement above (and the second, as hopefully there will be no objections). 

We shouldn't need anything for "documentation of changes that are not substantive", as we can point to the commit history. Our dependencies on other groups haven't changed, and the spec itself lists the known implementations.

It would also be great when we publish to have all the L2 stuff in PRs too, so we are good to proceed towards getting the additions merged into the main spec.

**Comment by mgiuca** [comment]
> It would also be great when we publish to have all the L2 stuff in PRs too, so we are good to proceed towards getting the additions merged into the main spec.

Do you mean to have them in unsubmitted PRs ready to do, so we can demonstrate that we're ready to add the new features?

**Comment by marcoscaceres** [comment]
> Do you mean to have them in unsubmitted PRs ready to do, so we can demonstrate that we're ready to add the new features?

Submitted, but unmerged, PRs would be better :) Then we can work towards getting public implementation commitment from a second implementer.

**Comment by mgiuca** [comment]
> Submitted, but unmerged, PRs would be better :)

Maybe we have a terminology difference. What is the difference between "submitted" and "merged" (I think of them as the same)? Do you mean reviewed but unmerged?

**Comment by marcoscaceres** [comment]
"merged" would be that we pressed the green button on the pull request, and it's in the actual spec. I'm saying the new additions should be just plain-old pull requests for now. When we get an 👍 from either WebKit or Mozilla that they are going to implement, then we would then merge them in.

**Comment by mgiuca** [comment]
I am, but if you think we should have the L2 stuff ready in PRs then we aren't ready for that yet.

I'll let you decide whether you think that's important enough to block on. If not, go ahead!

**Comment by marcoscaceres** [comment]
Ok, [CFC sent](https://lists.w3.org/Archives/Public/public-webapps/2019OctDec/0011.html). Gave two weeks.

**Comment by marcoscaceres** [comment]
Filled out issue, and sent request for publication for the 17th of December. https://github.com/w3c/transitions/issues/204

**Comment by marcoscaceres** [comment]
Updated template above... will kick off wide review after we get it published.

**Comment by marcoscaceres** [comment]
Closing as done. Will work with @LJWatson to kick off wide review.
