### ISSUE TITLE
Clarify how URL should be used on platforms without dedicated URL field

### ISSUE THREAD

**Issue by NotWoods** [w3c/web-share#130]
Similar to [Web Share Target's note](https://wicg.github.io/web-share-target/#obtaining-a-sharedata), the spec should clarify how to handle the URL property on platforms without a dedicated URL field (like Android). 

The desired behaviour is probably to put text and URL in the same field, since Web Share Target expects that.

**Comment by mgiuca** [comment]
We already say this in a non-normative note:

> Mapping the `ShareData` to the share target (or operating system)'s native format can be tricky as some platforms will not have an equivalent set of members. For example, if the target has a "text" member but not a "URL" member, one solution is to concatenate both the `text` and `url` members of `ShareData` and pass the result in the "text" member of the target.

But it's buried in the "Examples of share targets" section.

I've put up a PR (#131) that moves this up to a green box in the "Share targets" section so it's clearer, and also added "as is the case on Android" which we say in the Share Target spec.

I've also made a tiny normative change, which is to add "or combine" to the sentence "[The user agent] *MAY* discard or combine members if necessary."

That should resolve this issue.

**Comment by mgiuca** [comment]
> since Web Share Target expects that

Note that WST doesn't explicitly expect that (normatively). The spec allows WST implementations to look for that pattern, so it makes sense for WS implementations to produce it.
