### ISSUE TITLE
PDF share support 

### ISSUE THREAD

**Issue by ashishgehlot** [w3c/web-share#141]
Hello,

Sharing PDF files in not working. Other formats are working fine like (image,mp3 etc.).

I am using Web-share api 2. 

````

var file = new File(["/9j/4AAQSkZJRgABAQAAAQABAAD...."], 'filename.pdf', { type: 'application/pdf' });

var filesArray = [];

filesArray.push(file);

 navigator['share']({files: filesArray})
        .then(() => console.log('Share was successful.'))
        .catch((error) => console.log('Sharing failed', error));
````

I get this error : Sharing failed DOMException: Permission denied

**Comment by mgiuca** [comment]
Thanks for the report.

This is actually a Chrome-specific issue, not an issue with the spec. That's because Chrome allows only a designated set of file extensions, which does not include PDF.

I am in support of being able to share PDF. Follow https://crbug.com/1006055 for updates.

**Comment by beaufortfrancois** [comment]
FYI Chrome 93.0.4570.0 now supports sharing PDF files with Web Share. See https://chromiumdash.appspot.com/commit/7d30d42a018d4aa76fca2896f2903d892b5f5284 and https://bugs.chromium.org/p/chromium/issues/detail?id=1006055

**Comment by yaser-alazem** [comment]
I'm getting something similar for `vcard` files, is it also a Chrome related issue ?

```javascript
fetch('https://example.com/files/hello.pdf')
        .then(response => response.blob())
        .then(async res => {
          const file = new File([res], 'Raji_Sarhi_Profil.vcf', { type: 'text/x-vcard' });
          if (windowNavigator.canShare && windowNavigator.canShare({ files: [file] })) {
            await windowNavigator
              .share({
                files: [file],
                title: 'Kontakt Raji',
                text: 'Digitaler Kontakt von Raji.',
              })
              .then(() => alert('Contact shared successfully!'))
              .catch(error => alert('share error; ' + error));
          }
        });
```

I'm getting error on mobile `share error; notAllowedError: Permission denied`

**Comment by yaser-alazem** [comment]
I'm getting something similar for `vcard` files, is it also a Chrome related issue ?

```javascript
fetch('https://example.com/files/hello.vcf')
        .then(response => response.blob())
        .then(async res => {
          const file = new File([res], 'profil.vcard', { type: 'text/x-vcard' });
          if (windowNavigator.canShare && windowNavigator.canShare({ files: [file] })) {
            await windowNavigator
              .share({
                files: [file],
                title: 'Kontakt',
                text: 'Digitaler Kontakt.',
              })
              .then(() => alert('Contact shared successfully!'))
              .catch(error => alert('share error; ' + error));
          }
        });
```

I'm getting error on mobile `share error; notAllowedError: Permission denied`

**Comment by tomayac** [comment]
The currently supported file types (in Chrome) are [listed on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#shareable_file_types).

**Comment by yaser-alazem** [comment]
@tomayac thanks, just noticed that.

**Comment by yaser-alazem** [comment]
I'm not sure if there is an alternative way to share vcards?

**Comment by tomayac** [comment]
Since vCards are plaint-text ([example](https://datatracker.ietf.org/doc/html/rfc6350#section-8)), the best option might be to just share them as `text/plain`.

**Comment by yaser-alazem** [comment]
If it's been shared as a plain text file (`.txt` file), how can the sharing device know that it is a vacrd file in this case?

**Comment by tomayac** [comment]
Yeah, I know. Might be worth opening a [new.crbug.com](https://new.crbug.com/) where you request support to be added.

**Comment by yaser-alazem** [comment]
Sure, thanks Thomas.
