### ISSUE TITLE
File sharing not works on iOS

### ISSUE THREAD

**Issue by bogdyak** [w3c/web-share#142]
Hello

I am trying the following code. What I currently achieved is

```JavaScript
let text = "test"
let file = new File([text], "test.customtype", {
     type: "text/plain",
});
window.navigator.share({
    text: "It is test text",
    title: "it is text text",
    files: [file]
})
```

1. .txt file share on my android (ios shares only text)

2. sharing of text on both platforms

If i share `test.customtype` on android it fires an error: `Uncaught (in promise) DOMException: Permission denied`

Can't get logs on ios, sorry.

I would like to share .customtype file with my ios app or with any other app.

Really appreciate any advice.

**Comment by ewilligers** [comment]
The file sharing [spec](https://w3c.github.io/web-share/level-2/index.html#share-method) allows for

> a file type is being blocked due to security considerations

For example, Chrome on Android currently has lists of approved [file extensions](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/webshare/ShareServiceImpl.java?rcl=388f1d99762c033e470ace47d18f9ee44e874d7d&l=69) and [MIME types](https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/webshare/ShareServiceImpl.java?rcl=388f1d99762c033e470ace47d18f9ee44e874d7d&l=112).

I'm not familiar with the situation in other browsers, or on iOS.

This is not a spec bug.

**Comment by bogdyak** [comment]
@ewilligers Thank you.
Any reference on google plans to support custom file extensions?

**Comment by ewilligers** [comment]
> Any reference on google plans to support custom file extensions?

There isn't any decision or schedule. PDF support is being considered in https://bugs.chromium.org/p/chromium/issues/detail?id=1006055 .
