### ISSUE TITLE
Feature Policy integration

### ISSUE THREAD

**Issue by ewilligers** [w3c/web-share#151]
We should consider specifying

> The WebShare API is a [policy-controlled feature](https://w3c.github.io/webappsec-feature-policy/#policy-controlled-feature)  identified by the string "web-share". It's [default allowlist](https://w3c.github.io/webappsec-feature-policy/#default-allowlists) is 'self'. When disabled in a document, the share() method MUST return a promise which rejects with a "NotAllowedError" DOMException.

This way, the feature is disallowed by default in cross-origin documents in child browsing contexts.

**Comment by marcoscaceres** [comment]
Sounds great. We can probably integrate the second sentence directly into the `.share()` method algorithm.

**Comment by marcoscaceres** [comment]
Here is how we did it in Payment Request:
https://w3c.github.io/payment-request/#constructor

And: 
https://w3c.github.io/payment-request/#feature-policy

**Comment by ewilligers** [comment]
Chromium implementation task: https://bugs.chromium.org/p/chromium/issues/detail?id=1079104

**Comment by marcoscaceres** [comment]
Oh awesome! Will do the same on Gecko side. @ericwilligers, do you want me to draft up a PR?

**Comment by ewilligers** [comment]
I don't know how to write a WPT for this one.

**Comment by marcoscaceres** [comment]
We can copy these: https://github.com/web-platform-tests/wpt/pull/23729

**Comment by marcoscaceres** [comment]
With those tests, we can replace all the geo stuff for "share". It should be fairly straight forward.
