### ISSUE TITLE
Note about choice of USVString imprecise

### ISSUE THREAD

**Issue by aphillips** [w3c/web-share#152]
WebShare
https://w3c.github.io/web-share/#sharedata-dictionary

> These members are USVString (as opposed to DOMString) because they are not allowed to contain invalid UTF-16 surrogates. This means the user agent is free to re-encode them in any Unicode encoding (e.g., UTF-8). 

The above "Note" about the choice of USVString over DOMString is imprecise. I18N would suggest the following wording instead:

> These members are USVString (as opposed to DOMString) because they are not allowed to contain surrogate code points. Among other things, this means that the user agent can serialize them into any Unicode encoding, such as UTF-8, without change or loss of data or the generation of replacement characters.

**Comment by marcoscaceres** [comment]
@aphillips, just confirming that the text you suggested is in the spec. See the note:

https://w3c.github.io/web-share/#sharedata-dictionary

Could you (or @xfq?) kindly remove the i18n-needs-resolution label if you are satisfied?

**Comment by aphillips** [comment]
@marcoscaceres Thanks for making this change. I am satisfied by the modification.

Please do not remove the `i18n-needs-resolution` label. It's how we can find this issue again (which assists in our closing our mirror issue w3c/i18n-activity#901, which is how you get a clean bill of health at transition time). You are welcome to close the issue.

**Comment by aphillips** [comment]
In our [teleconference today](https://www.w3.org/2022/08/04-i18n-minutes.html#t07), the I18N WG confirmed that we are satisfied.

**Comment by hober** [comment]
Perhaps this should reference https://www.w3.org/TR/design-principles/#idl-string-types ?
