### ISSUE TITLE
w3c/web-share

### ISSUE THREAD

**Issue by elrussord** [w3c/web-share#163]
if (!window.PublicKeyCredential) { /* Client not capable. Handle error. */ } // credentialId is generated by the authenticator and is an opaque random byte array var credentialId = new Uint8Array([183, 148, 245 /* more random bytes previously generated by the authenticator */]); var options = { // The challenge is produced by the server; see the Security Considerations challenge: new Uint8Array([4,101,15 /* 29 more random bytes generated by the server */]), timeout: 120000, // 2 minutes allowCredentials: [{ type: "public-key", id: credentialId }] }; navigator.credentials.get({ "publicKey": options }) .then(function (assertion) { // Send assertion to server for verification }).catch(function (err) { // No acceptable credential or user refused consent. Handle appropriately. });

**Comment by ewilligers** [comment]
This issue doesn't seem to be about [Web Share API](https://w3c.github.io/web-share/).
