### ISSUE TITLE
files members should be a sequence, not a FrozenArray

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#165]
When passing dictionaries as arguments, `FrozenArray` doesn't make much sense, as: 

 1. dictionaries are passed by value
 2. it implies that `dictionary.files = Array.freeze([...files]);`, which is really what is mean there.

Related discussion https://github.com/heycam/webidl/issues/900

**Comment by ewilligers** [comment]
I have no concerns.

Chromium change would be [trivial](https://chromium-review.googlesource.com/c/chromium/src/+/2327774).
