### ISSUE TITLE
Add intent parameter

### ISSUE THREAD

**Issue by dshanske** [w3c/web-share#168]
To allow for improving the user experience, allow for an optional parameter/attribute that shows the intent or the activity. As more and more share targets get registered, having this verb can filter them.

Example, intent is 'bookmark' so only sites that support bookmarking could be suggested. Any software that didn't support this would simply show all targets.

**Comment by marcoscaceres** [comment]
This is good idea @diekus, but currently out of scope (but I think it's good to continue the discussion at https://github.com/w3c/web-share-target/issues/98) - so I'm going ahead and closing.
