### ISSUE TITLE
Improve public documentation for Web Share

### ISSUE THREAD

**Issue by mgiuca** [w3c/web-share#17]
We received a lot of requests from the Chrome Origin Trial for Web Share for improving the documentation.

Aside from writing a proper spec, we should get some dedicated developer docs (possibly coordinating with MDN).

**Comment by ewilligers** [comment]
samthor has contributed [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)

**Comment by ewilligers** [comment]
Joe Medley wrote [Share like a native app with the Web Share API](https://web.dev/web-share/).
