### ISSUE TITLE
Purpose of the sharePromise?

### ISSUE THREAD

**Issue by plinss** [w3c/web-share#179]
From the [TAG review](https://github.com/w3ctag/design-reviews/issues/554):

Exposing a global sharePromise seems redundant since the promise is returned by the share method.

Unless this provides some concrete benefit beyond what the user could get by simply storing the return value in a global of their choosing, we recommend removing it.

**Comment by ewilligers** [comment]
A benefit of the global sharePromise is described in https://bugs.chromium.org/p/chromium/issues/detail?id=1002337#c4 by an author requesting Chrome implement it:

> If you tap the share button in the top right corner quickly on Android you can get multiple share sheets stacked on top of each other in on Android 11. For users who's hands shake this is pretty frustrating, you can very easily get several shares by mistake.

Every author could avoid this Accessibility shortcoming by "simply storing the return value in a global of their choosing" but it seems better to make "Only allow one share() call at a time" the default.

**Comment by plinss** [comment]
That's a fair point, but could also be achieved by the share method either returning the existing promise when one is already active, or probably better, rejecting a second call if made before the existing call resolves. Neither of which requires exposing the promise as an attribute of Navigator.

**Comment by saschanaz** [comment]
I think sharePromise is not exposed as an attribute, as it's just an internal slot.

**Comment by marcoscaceres** [comment]
Yeah, it's an internal guard/concept. As @saschanaz says, it's not exposed to web content directly. Implementations could represent it in other ways, but just using the promise works fine to prevent multiple shares occurring at once. 

@plinss make sense? I don't think we want to change this.

**Comment by ewilligers** [comment]
Blink has just implemented it, to ship in Chrome 87.

**Comment by marcoscaceres** [comment]
Same, [implemented and shipped in Firefox](https://github.com/mozilla/gecko-dev/blob/master/dom/base/Navigator.cpp#L1383).

**Comment by plinss** [comment]
Right, it's not exposed, sorry for misinterpreting that. I blame getting up early for a VF2F and, well, 2020 in general.

Re-reading I see that the purpose is to reject a second call if the first promise is unresolved to avoid multiple stacked share sheets, which is I agree is an issue. I'm fine with this approach.

**Comment by marcoscaceres** [comment]
Sent request to TAG to remove label https://lists.w3.org/Archives/Public/www-tag/2022Aug/0000.html
