### ISSUE TITLE
navigator.share in webviews

### ISSUE THREAD

**Issue by vjbobeldijk** [w3c/web-share#190]
navigator.share works like magic in javascript on my https page on my android phone.with chrome.

However, when opening my internet page with the url sent  to  messenger, and messenger opening in it's own (internal) browser, navigator share doesn't work with my share  button.

I read somewhere that navigator.share doesn't work in webviews.

I searched for ways to force open chrome from within the messenger browser, but all myattempts failed with javascript.
I don't want an app.

Does anyone know if this webview issue will be solved ?

(Btw I could build my own share button. But I didn't find the  code to open the messenger contact list).

**Comment by tomayac** [comment]
This API is unlikely to be ever exposed on WebViews, since the WebView could be just a tiny fragment of an app's screen:

```
Native Component
Native Component
Native Component
WebView
Native Component
Native Component
```

For the last remark, there is no specific messenger browser API, but there is a [Contact Picker API](https://web.dev/contact-picker/) on Android.

**Comment by vjbobeldijk** [comment]
Thank you ! I will try the contact picker API.

Force opening e.g. chrome or safari could be a solution as well, if it would work on a javascript website,
but I didn't find a working piece of code yet in javascript on a html/php page. 

Adding a message with instructions how to open an external browser on android or iphone is a solution too,
but I don't like it.

**Comment by tomayac** [comment]
I guess sometimes it's part of the product strategy of apps that deliver their own in-app browser to make breaking out of this experience difficult.

**Comment by vjbobeldijk** [comment]
I guessed so too. I understand that strategy not wanting people to leave.

Though the navigator share as a means to get into these browsers,  would be a nice 
extra in the case of fb messenger to get back in.
But it's not in the hands fo fb maybe to change navigator share not working in a webview.

**Comment by ewilligers** [comment]
This isn't a spec issue. For issues with specific browser engines, [Chromium](https://crbug.com/) or [WebKit](https://bugs.webkit.org/) or [Mozilla](https://bugzilla.mozilla.org/home) bugs can be used.
