### ISSUE TITLE
Screen Freeze with WebGL Build

### ISSUE THREAD

**Issue by asyranamin** [w3c/web-share#191]
I've been trying to get webshare api to work in a unity WebGL build. 
At first, everything was working normally. but then recently, maybe a week or two ago, it stopped working. whenever we open the native sharing module, the whole screen freezes, unable to tap on any UI elements within the UnityContainer or html button. 
An observation that was made seem to be that the UI of the native sharing had changed. instead of a potrait style box coming up, now there's a landscape style UI that pops up. Not sure if there was an update to the native way chrome handles the new share request. 
Could there be a way to solve this issue? Thanks. 

Original Native Pop Up with no issues.
![WhatsApp Image 2020-11-10 at 19 37 17](https://user-images.githubusercontent.com/59105221/98773671-5fd2b880-2424-11eb-9742-dd67ef2a012b.jpeg)

Updated Native Pop Up with Issues. 
![WhatsApp Image 2020-11-10 at 19 37 26](https://user-images.githubusercontent.com/59105221/98773680-62351280-2424-11eb-8aa4-5b00a824554d.jpeg)

**Comment by ewilligers** [comment]
For Chrome WebShare issues, use [Component: Blink>WebShare](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebShare) in the Chromium bug tracker.

**Comment by mgiuca** [comment]
The bottom is Chrome's new share sheet launched in Chrome 86 as far as I can tell. That's working as intended, but it shouldn't be crashing.

As Eric said, you need to [file a bug against Chrome](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EWebShare), not the W3C spec.
