### ISSUE TITLE
Cultural Heritage use cases for web share

### ISSUE THREAD

**Issue by tomcrane** [w3c/web-share#194]
Hi, 

I'm one of the editors of the [International Image Interoperability Framework](https://iiif.io/) (IIIF) specifications. IIIF is a standard for describing complex digital (usually digitised) objects, such as books, manuscripts, maps, movies, radio programmes and so on. It's used by Libraries, Museums and academic institutions to publish their collections.

A common use case is viewing an object in one environment - perhaps the publishing institution's web site, like this:

https://collections.library.yale.edu/catalog/2002046

... and wanting to take that object into a different web environment, such as your preferred viewer, or an annotation tool so that you can make some notes about it:

https://mirador-dev.netlify.app/__tests__/integration/mirador/

The community has in the past adopted an informal drag-and-drop pattern, which is unsatisfactory for many reasons. We've been working on a new specification, which provides patterns for software implementations to share _content state:_ how do I send what I'm looking at right now, over to my friend, or to another web application?

https://iiif.io/api/content-state/0.3/

The Web Share API seems an obvious way of doing this. We think we should add a new section to part 3 of the spec, to accompany the other recommended patterns there (e.g., here's a formalised version of drag and drop: https://iiif.io/api/content-state/0.3/#initialization-mechanisms-dragdrop). But before we do that, we wanted to reach out, to see if you are interested in the usage scenarios identified in that specification document.

The spec covers not just the sharing of a page-level URL, but the ability to share arbitrarily complex targeted parts of a resource. In this case they are IIIF Presentation API resources. The targeting mechanism is [W3C Web Annotations](https://www.w3.org/TR/annotation-model/), so exactly the same mechanism could be used to target HTML elements of a page and share them - such as paragraphs or for highlighting text ranges.

**Comment by ewilligers** [comment]
If we only supported sharing to other web sites, I expect we would have the option of making the share data arbitrarily rich.

However, we support sharing to non-browser native applications on the host platform. The share sheet (chooser dialog) is typically implemented by the host operating system. If the user happens to choose a web application as the share destination, then the operating system typically launches a browser.

Thus the shared data is effectively limited to what operating systems typically support, e.g. title, text, files.

**Comment by azaroth42** [comment]
Hi @ewilligers :) While @tomcrane expressed it in terms of web applications, it would also be great if it was available for native applications or browser extensions. Given that the state can be expressed as a URL (by base64 encoding the Web Annotation that describes it), I think we can use the existing OS supported features. It's good to know that there isn't scope for extending the current set of sharable properties, and we need to stick within title, text and url.

**Comment by marcoscaceres** [comment]
closing as answered. We don't intend to take any action based on this issue.
