### ISSUE TITLE
Share Excel Files Extensions

### ISSUE THREAD

**Issue by deybich** [w3c/web-share#198]
I would like to know if the API isn't still able to share excel file.

**Comment by marcoscaceres** [comment]
The API itself does not put restrictions on what can be shared, via `files:`. However, when passed to the OS, it might not know what to do with those files - but, again, this is not an API issue. It's likely an implementation issue on whatever platform you are trying to share on. 

@deybich, can you provide a few more details on which platform you are trying to do this on? I assume Windows?

**Comment by deybich** [comment]
I was try to share .xlsx file in a PWA created in ionic, currently I'm using this share API in PWA through android device and I achieved to share CSV file to read it in excel but a XLSX is not allowed

**Comment by marcoscaceres** [comment]
Ok cool. One of the Chrome folks might have something to say, but this is sounding like an Android related issue.

**Comment by ewilligers** [comment]
Chrome currently restricts the [file types](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/webshare/FILE_TYPES.md) that may be shared.

The list was initially conservative, to minimize the possibility of Web Share being used to spread malware, such as executable binaries and [malware malware](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/macro-malware#how-macro-malware-works).

We may be able to wind back the restrictions.

**Comment by deybich** [comment]
In fact, I remember getting an error message about permission or something like that in the CanShare evaluation, probably that is the case

**Comment by marcoscaceres** [comment]
Closing as answered, as this is a bit outside the scope of the spec itself.
