### ISSUE TITLE
Web Share Api for WebViews

### ISSUE THREAD

**Issue by victormarllam** [w3c/web-share#199]
Hello,
Is there any choice about this API working for WebViews?

Also, in which technologies is built this project? I see that all commits just modify index.html

**Comment by saschanaz** [comment]
This repository is not about any implementations. If you are talking about Android WebView, the issue should be filed in https://issuetracker.google.com/issues?q=componentid:192693%2B.

**Comment by ewilligers** [comment]
Here is the existing bug for Android WebView:
https://bugs.chromium.org/p/chromium/issues/detail?id=765923
