### ISSUE TITLE
Test is conflicting with the spec

### ISSUE THREAD

**Issue by arthuro555** [w3c/web-share#202]
Hello, I am not sure if this is the right place to talk about this, but one of the tests in the test suite specified in the specification document is testing against something conflicting with the specification. I am talking about [this test](https://w3c-test.org/web-share/share-url-data-manual.https.html). It is testing if it is possible to pass a `data:` url as parameter. However, the spec states under [2.1.2](https://www.w3.org/TR/web-share/#share-method).8.4 that 

> If url's scheme is not "http" or "https", return a promise rejected with TypeError.

As it is returning, it will never reach step 11 where the URL is transmitted to target.

Did I misunderstand something in the specification in any way?

**Comment by saschanaz** [comment]
#174 added that step, it seems tests wasn't checked back then.

**Comment by ewilligers** [comment]
Many of the tests previously used `data:`

The spec restriction to `http:` or `https:` was only added recently - see #173. 

The test can be updated to use `https:`

**Comment by marcoscaceres** [comment]
Closed via https://github.com/web-platform-tests/wpt/pull/28654
