### ISSUE TITLE
Discussion: `navigator.share.qrCode` 

### ISSUE THREAD

**Issue by tomayac** [w3c/web-share#204]
Chromium has added an option to get a QR code for the current URL via the URL bar. It would probably be useful to expose this feature as a browser API on all form factors to let developers add QR code generation as a feature to their apps. A possible location could be…

```js
const blob = navigator.share.qrCode('text', {
  format: 'image/png', // optional
  size: 512, // optional
});
```

This would return a QR code image blob that developers could then show according to their own needs. I believe it could be a synchronous function, since no permission would be required. 

(Original idea via this [tweet](http://twitter.com/AaronGustafson/status/1398053386738573318).)

**Comment by marcoscaceres** [comment]
It wouldn't be ideal to have a particular type of share specifically for QR codes, but are QR codes identifiable as a media type? I've never looked at how they are created/structured or if they are even standardized, but maybe just sharing as `files` could work? 

I think it goes roughly blob with media type -> QR code representation.

**Comment by tomayac** [comment]
> It wouldn't be ideal to have a particular type of share specifically for QR codes […] 

Something else that's quite common is to share a PDF version of the page or (probably less common) a web archive version of the page ([example link](https://www.techrepublic.com/article/how-to-archive-websites-as-pdfs-and-web-archives-in-ios-14/#:~:text=Select%20the%20Share%20button%20in,Select%20Done.)). So QR code would not need to be the only option. Maybe `navigator.shareAs()` then?

> [A]re QR codes identifiable as a media type? I've never looked at how they are created/structured or if they are even standardized […]

They are to become an [ISO standard](https://www.iso.org/standard/76478.html), but I don't think they will have a [media type](https://www.iana.org/assignments/media-types/media-types.xhtml).

> [M]aybe just sharing as `files` could work?

Unsure about the plural here.

**Comment by marcoscaceres** [comment]
> Something else that's quite common is to share a PDF version of the page or (probably less common) a web archive version of the page (example link). 

Isn't this just part of the page/browser UI (I.e., standard browser share stuff)? For installed PWAs then, maybe what we actually want is just:

```JS
// Share this top-level browsing context
navigator.share(); 
```

Which would bring up the share "default" share for the page? On iOS/Android, then the use can share as PDF, Web Archive, or whatever new thing thing gets added to share at the OS level in the future. 

> They are to become an ISO standard,

/me shakes first!!!, "USD$70 to view a standard! Curse you IIIISSSOOO!!!" 😆

> Unsure about the plural here.

The plurals are handled by the OS share... if it only gets one thing, then it knows what UI to show. For example, IIRC, this is already supported for images (single image VS multiple images get different share UIs).

**Comment by saschanaz** [comment]
It could be a good idea to reconsider #180 if we want this.

**Comment by marcoscaceres** [comment]
I still think this should just be a "file"... or at least, we should see if it can't be a file.

**Comment by tomayac** [comment]
The original idea from this Issue was to tap into browser-facilitated share methods, like Chrome's [Create QR code for this Page](https://support.google.com/chrome/answer/9979877?hl=en&co=GENIE.Platform%3DDesktop), so people don't need to pull in a QR code generation library but could use the browser's.

**Comment by marcoscaceres** [comment]
Ah, lol! sorry!!! I had misunderstood as I've not seen this before. Just found it in Chrome. That's super cool!!!!! :D 

So, maybe something like 

```JS
navigator.share({ url: "other thing", as: "qr" });
navigator.share({ text: "some text", as: "qr" });
```

**Comment by tomayac** [comment]
> Ah, lol! sorry!!! I had misunderstood as I've not seen this before. Just found it in Chrome. That's super cool!!!!! :D

My bad, I could have added a help link to the initial post instead of just describing the feature and assuming people are aware.

> So, maybe something like
> 
> ```js
> navigator.share({ url: "other thing", as: "qr" });

`url` should probably be a URL:

```js
navigator.share({ url: location.href, as: "qr" });
```

> ```js
> navigator.share({ text: "some text", as: "qr" });

Yeah, it's a hidden power-feature that the text can be changed. So +1 to exposing it!

Additional options could be `as: "mhtml"` (a feature of the **File > Save As** dialog) and `as: "pdf"` (a feature of the **File > Print…** dialog). These would silently assume the `url` is the URL of the current page. Would this work?

**Comment by marcoscaceres** [comment]
I like where this is going :) it has the nice quality that it has fallback model.

**Comment by saschanaz** [comment]
How could this be feature detected?

**Comment by tomayac** [comment]
> How could this be feature detected?

Maybe by extending [`navigator.canShare()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/canShare)?

**Comment by saschanaz** [comment]
`canShare()` itself has a problem where a new field will be always ignored by an older implementation. I would prefer an existence check rather than complicating already-problematic one.

**Comment by marcoscaceres** [comment]
Should this be feature detectable? It's aspirational.

**Comment by saschanaz** [comment]
> Should this be feature detectable?

Well, it would be confusing to request a qr code and then get a plain share dialog?

**Comment by marcoscaceres** [comment]
could be... but I think that's a UX thing. Like the UI could allow the user to just switch it to normal text/url/whatever.

**Comment by marcoscaceres** [comment]
(and the other way around too... like, I could share a URL and have something in the UI show it as a QR code)

**Comment by saschanaz** [comment]
That would be cool and would probably not require adding any API.

**Comment by marcoscaceres** [comment]
Closing for now, as it seems possible to simply share the URL and have the share target or user agent present it as a QR code.

**Comment by SaadBazaz** [comment]
Is there a way to "tell" the user-agent that we prefer sharing as a QR? 
It's akin to Chrome's own functionality:
<img width="720" alt="image" src="https://github.com/w3c/web-share/assets/51885228/a33c2218-15da-4747-a431-d8fdea30585a">
