### ISSUE TITLE
Plan to transition to CR

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#207]
Hi @mgiuca, @ericwilligers, just pinging as Web Apps Chair. The W3C would like to see if we can finish off this spec and transition it to CR. 

Any objections to me merging:
 
 * https://github.com/w3c/web-share/pull/185
 * https://github.com/w3c/web-share/pull/177

And closing:

 * https://github.com/w3c/web-share/pull/184
 * https://github.com/w3c/web-share/pull/72

I think we are then good to kick off wide review and transition this to CR.

**Comment by marcoscaceres** [comment]
Will use the https://github.com/w3c/transitions/issues/new/choose for guidance instead.

**Comment by ewilligers** [comment]
No objections.
