### ISSUE TITLE
Two Clarifications

### ISSUE THREAD

**Issue by hamishwillee** [w3c/web-share#213]
1. Spec changed from referring to files as a "Frozen Array" to a sequence. I have not heard of a frozen array before - can you tell me how a sequence differs practically from an array in Javascript? (or what type of Array this would mean?)
2.  The share validation ends with two points:
   - Once the data has either been successfully transmitted to the share target, or successfully transmitted to the OS (if the transmission to the share target cannot be confirmed), resolve [[sharePromise]] with undefined.
   - Set [[sharePromise]] to null.

When does the last point happen? i.e. as a user I see my promise resolved with `undefined` - when does the setting of this value to `null` happen? I'm still working on my javascript so this may be a stupid question sorry!

**Comment by marcoscaceres** [comment]
Closing as answered.

**Comment by hamishwillee** [comment]
Yes it is. Thanks!!!
