### ISSUE TITLE
Define what "hostile share" is

### ISSUE THREAD

**Issue by saschanaz** [w3c/web-share#217]
From https://github.com/mdn/content/pull/8381#discussion_r698115221:

https://w3c.github.io/web-share/#validate-share-data

>If the user agent believes sharing any of the files in files would result in a potentially hostile share, return false. 

But the spec does not say what can be a "potentially hostile share".

**Comment by saschanaz** [comment]
BTW, from what I see WebKit and Blink don't check such thing in `canShare()`. Should it be moved to `share()` instead?

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webshare/navigator_share.cc;l=77-104;drc=92b21970ffc4d2333c5081ccd1175d6c0ed9c6b0

https://webkit-search.igalia.com/webkit/rev/d9197df94519d81a87789468cb0a37d7f5c4048c/Source/WebCore/page/Navigator.cpp#128-145

**Comment by ewilligers** [comment]
Blink could be updated to match the spec, making `canShare()` more useful.
