### ISSUE TITLE
canShare file "save image" does not resolve navigator

### ISSUE THREAD

**Issue by domtripodi** [w3c/web-share#221]
I have found a possible bug on IOS15 where the navigator does not completely resolve. 

I have been testing the sharing of files with navigator.canShare() and more specifically have been testing sharing image files. 
When testing on an iPhone on IOS15, when you attempt to share an image, if you select the "Save Image" option (saves image to photos application), the navigator closes but does not resolve. 

This can be replicated on the demo page (the share buttons become blocked and it does not fail or succeed): 
https://w3c.github.io/web-share/demos/share-files.htm
![IMG_6242 3](https://user-images.githubusercontent.com/24926301/137854903-4e9ac6be-4578-441e-a1e9-8d5efa10fc92.PNG)

I am unsure if this is the place to report this! I believe it is important because when the navigator does not resolve, it means it cannot be called again in the same context which leads to unwanted exceptions.

**Comment by ewilligers** [comment]
iOS browser bugs should be reported to [WebKit](https://bugs.webkit.org/).

**Comment by marcoscaceres** [comment]
Thanks @domtripodi! Can you drop a link to the Webkit bug here? I might also be able to take a look.

**Comment by marcoscaceres** [comment]
Thanks @domtripodi! Closing as we can now be tracked on the WebKit side 🙏

**Comment by DEVfancybear** [comment]
+1
