### ISSUE TITLE
Share not display image

### ISSUE THREAD

**Issue by DEVfancybear** [w3c/web-share#222]
After sharing, only the link is displayed, not the uploaded image.

**Comment by marcoscaceres** [comment]
Hi @DEVfancybear, this repository is for specification, not for a particular browser. However, if you tell us which browser you are having an issue in, we might be able to point you in the right direction.

**Comment by DEVfancybear** [comment]
@marcoscaceres I'm getting an error sharing images but only showing the link in safari browser, can you help me

**Comment by marcoscaceres** [comment]
If you put the share() code up somewhere, I can check if it’s a browser bug or not.

**Comment by DEVfancybear** [comment]
![code](https://user-images.githubusercontent.com/47390684/141873649-920e0d4f-7e89-4428-b57e-6b92176d942c.png)
I have tested this code on adnroid and it works as I want, but when using on ios safari, when I share the image, I only get the link, for example telegram or skype are not displayed.

**Comment by marcoscaceres** [comment]
Thanks @DEVfancybear. I can't see anything obviously wrong, so it might be a bug or limitation in Safari. 

I'll see if I can track down someone from the WebKit team to see if they can reproduce the issue.

**Comment by DEVfancybear** [comment]
![9](https://user-images.githubusercontent.com/47390684/142366969-33bab7fe-53cc-465c-80e2-542b1968b30b.png)
![8](https://user-images.githubusercontent.com/47390684/142366991-fb4cc2ee-08a6-4895-8f4e-25fe97b0c437.png)
If I select only update vs file, not url, text, title, will the new iphone device like iphone 12 promax show such error @marcoscaceres ?

**Comment by DEVfancybear** [comment]
![9](https://user-images.githubusercontent.com/47390684/142367242-0058dbf4-68c9-4431-b762-cc9b787d8088.png)
If I select only update vs file, not url, text, title, will the new iphone device like iphone 12 promax show such error @marcoscaceres ?

**Comment by marcoscaceres** [comment]
@DEVfancybear could you please put the actual file you are testing again somewhere? I.e., it may be that the browser supports it, but it's not actually shareable for other reasons.

**Comment by DEVfancybear** [comment]
But in the picture is the error Unsupported feature: navigator.canShare() @marcoscaceres ?

**Comment by marcoscaceres** [comment]
@DEVfancybear please understand that it’s not possible for me to replicate the problem without all the same code+data.

**Comment by saschanaz** [comment]
The demo looks wrong btw. It shouldn't fail with canShare-is-unsupported message.

https://github.com/w3c/web-share/blob/6b868ff580fd4bd300a06067b41ff6bb359de3c6/demos/share-files.html#L133-L136

**Comment by DEVfancybear** [comment]
> @DEVfancybear please understand that it’s not possible for me to replicate the problem without all the same code+data.

I'm using the web demo of this project :(

**Comment by saschanaz** [comment]
The demo has been updated. What does it say when you retry?

**Comment by marcoscaceres** [comment]
Closing as this is not really a spec issue and in light of #226. Happy to keep discussion going if need be.
