### ISSUE TITLE
Split security & privacy considerations

### ISSUE THREAD

**Issue by samuelweiler** [w3c/web-share#224]
Please split security and privacy considerations into separate sections, as it has been claimed was done here, but appears to have not yet been done.  https://github.com/w3c/security-request/issues/17#issuecomment-968988827

**Comment by samuelweiler** [comment]
We have changed the guidance, and while separate security and privacy sections are still recommended, they are not required.  Feel free to close this issue or not, as you prefer.

**Comment by marcoscaceres** [comment]
Hi @samuelweiler, as a followup, we've integrated the security requirements more directly into normative sections of the spec. The Privacy section now describes the privacy mitigations are in place throughout the spec.
