### ISSUE TITLE
File size limitations - MP4 

### ISSUE THREAD

**Issue by JohnRubado** [w3c/web-share#225]
Hello! I am attempting to share mp4 files that can be anywhere from 10-80 MB. Some files work, while others fail with Permission Denied and a Share too large warning message. 

What are the file size limits? and are the file size limits specific to anything like the browser or file type?

Also, if there is documentation that has this info please let me know, I can't seem to find it. 

Thank you

**Comment by marcoscaceres** [comment]
Hi @JohnRubado! The specification doesn’t enforce any limitations but browsers themselves might (which sounds like what you hit). Which browser and/or OS is this on?

**Comment by ewilligers** [comment]
For example, Blink rejects shares with more than 10 files, or where the total of the file sizes exceeds 50MB.

**Comment by marcoscaceres** [comment]
I think we could give some examples as part of #217

**Comment by JohnRubado** [comment]
It does seem like it is a browser restriction. I am getting the same error on both Android 12 Chrome 96, Windows Chrome 96, and Windows Edge.  

We want to support sharing video files to tiktok, instagram, and youtube and we meet all their file size restrictions but we are blocked by this size restriction on the browser unfortunately

**Comment by marcoscaceres** [comment]
As the above doesn't affect the spec, I'm going ahead and closing this. If this is still an issue, it might be good to raise over on [blink-dev](https://groups.google.com/a/chromium.org/g/blink-dev) maybe?
