### ISSUE TITLE
Should sharing zero size files be allowed?

### ISSUE THREAD

**Issue by tomayac** [w3c/web-share#229]
Should sharing of an opaque response be allowed?

```js
try {
  const url = 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png';
  const blob = await fetch(url, {mode: 'no-cors'}).then(response => response.blob());
  const file = new File([blob], 'image.png');
  const data = {
    files: [file]
  };
  if (!navigator.canShare(data)) {
    throw new Error('Cannot share');
  }
  await navigator.share(data);
} catch (err) {
  console.error(err.name, err.message);
}
```

For this example, `navigator.canShare()` returns `true`, but the actual share operation then fails. Play with this [example](https://cut-deep-ankle.glitch.me/) deployed.

Possibly related: https://github.com/w3c/web-share/issues/173

**Comment by annevk** [comment]
Why would `response.blob()` not throw here?

**Comment by saschanaz** [comment]
Gecko does not throw on `.blob()` here either, btw.

**Comment by annevk** [comment]
Yeah, I realized after posting that it likely won't fail, but the blob will be empty so you won't end up sharing anything.

**Comment by marcoscaceres** [comment]
Is just checking if the file is zero size sufficient? If yes, we could just add that check for each file.

**Comment by marcoscaceres** [comment]
Alternative: filter out all zero length files. If results in empty list of files, return false.

**Comment by marcoscaceres** [comment]
@tomayac, what do you think? Drop the empty files on the floor (and do nothing if they are all empty)? It seems like the most user friendly solution.

**Comment by saschanaz** [comment]
An empty file still has some info (the filename) so I wonder implicitly filtering it out may add some confusion.

**Comment by marcoscaceres** [comment]
Well, it depends On MacOS's various handlers it's kinda confusing, because some apps just spin up with nothing to share (e.g., in Notes.app). Others show an empty preview of a file. For example:   

<img src="https://user-images.githubusercontent.com/870154/171069881-6c65323a-d321-4905-94c9-a0f8e0c68257.png" width="200">

When normally you would see a preview:

<img src="https://user-images.githubusercontent.com/870154/171069948-c1382524-760b-466a-b68c-e21d11cc7130.png" width="200">

What happens on Windows?

**Comment by saschanaz** [comment]
Looks like this when an "Share to" item is selected:

![image](https://user-images.githubusercontent.com/3396686/172213244-a9eeebdb-ab66-4599-ab3e-b151a786f4c2.png)

**Comment by marcoscaceres** [comment]
Ok, let's got with doing nothing here. Developer should decide and, if they so choose, filter out empty files for situations like @tomayac found. However, for certain applications (e.g., text), it could make perfect sense to share an empty text file with just a file name.
