### ISSUE TITLE
What's the reason to remove web intents from web share besides security concerns

### ISSUE THREAD

**Issue by chenmently** [w3c/web-share#232]
I understand the security issue, per the W3C draft, that the web app which initializes the share shouldn't any information from share target. But I would argue that returning share results can be useful, for example, getting a translated text from a translate service either from native or web app to replace origin text,  and we can possible design a permission system such as the notification one to mitigate security risk. So what's the benefit of giving no return values and what's the potential problem with other design

**Comment by marcoscaceres** [comment]
It sounds like this would create some kind of bi-directional cross-origin communication channel, which is not really what we want (or the purpose of the API). 

Couldn't both app register themselves as share targets to pass data back and forth? (but keeping the user in control). 

For example: 

 1. Translate app is a share target. 
 1. Text app is a share target.

Text app -> share text with Translate. Then, Translate app -> share text with Text app. 

There are also other ways to achieve the same thing by other means. Like Text App could authenticate with Translate app, and then be authorized to use it as service (via fetch API).

**Comment by ewilligers** [comment]
Also note that Web Share and Web Share Target are not designed in a vacuum purely for interaction between web apps. Operating Systems have their various (but similar) ways for apps to send shared data, and to receive shared data. To my knowledge, they don't provide a mechanism for return values.

Browsers typically implement Web Share by forwarding shared data to the operating system, and implement Web Share Target by registering web apps with the operating system.
