### ISSUE TITLE
Call for Consensus: Publish as Candidate Recommendation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#246]
This is a call for consensus (CFC) to publish the [Web Share API](https://www.w3.org/TR/web-share/) specification as a [Candidate Recommendation](https://www.w3.org/2021/Process-20211102/#transition-cr). 

The CFC ends at midnight on Friday the 29th of July, 2022. 

You can view the latest working draft here (synced with Editor's draft):
https://www.w3.org/TR/web-share/

The abstract reads: 

> This specification defines an API for sharing text, links and other content to an arbitrary destination of the user's choice.
> The available share targets are not specified here; they are provided by the user agent. They could, for example, be apps, websites or contacts.

The API has received [wide review](https://www.w3.org/2021/Process-20211102/#wide-review) and is implemented in an interoperable manner across all major browser engines across a range of platforms and has wide usage across the Web. 

However, the specification identifies one feature at risk: 

 * #169 - due to web compatibility issues. 

Please indicate your support for publishing the specification as a W3C Candidate Recommendation in the Github issue linked below using either the 👍 or 👎 (formal objection) reaction buttons of this issue. If you have an formal objection (i.e., you indicate 👎) to its publication, we kindly ask that you raise it before 29th of July, 2022:  https://github.com/w3c/web-share/issues/246

**Comment by siusin** [comment]
The CFC ends with 11 supports. Thank you all!
