### ISSUE TITLE
Call for consensus: publish as a Proposed Recommendation

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/web-share#253]
This is a call for consensus (CFC) to publish the [Web Share API](https://www.w3.org/TR/web-share/) specification as a [Proposed Recommendation](https://www.w3.org/2021/Process-20211102/#transition-pr).

**The CFC ends at midnight 23 November, 2022.**

Please indicate your support for publishing the specification as a W3C Proposed Recommendation in the Github issue linked below using either the 👍 or 👎 (formal objection) reaction buttons of this issue:
https://github.com/w3c/web-share/issues/253

If you have a formal objection (i.e., you indicate 👎) to its publication, we kindly ask that you raise it before 23 November, 2022.

The specification had identified one "feature at risk" (#169), which is now resolved and interoperable across all user agents. 

You can view the latest working draft here (synced with Editor's draft):
https://www.w3.org/TR/web-share/

The API has received [wide review](https://www.w3.org/2021/Process-20211102/#wide-review) and is implemented in an interoperable manner across all major browser engines and across a range of platforms. It also has wide usage across the Web.

**Comment by siusin** [comment]
Thank you. This CFC closed with only support.
