### ISSUE TITLE
Is implemented

### ISSUE THREAD

**Issue by lemanschik** [w3c/web-share#254]
i guess this is part of my web-modules standard

- https://github.com/lemanschik/web-modules
- [ ] https://github.com/microsoft/vscode/issues/167505

**Comment by saschanaz** [comment]
Amazing AI generated spam.

**Comment by lemanschik** [comment]
@saschanaz thats not spam i am real?

**Comment by lemanschik** [comment]
@saschanaz nur weil ich implementiert hab ohne proposals ist das kein grund zu denken das es fake ist ich ziehe das durch ohne w3c ich brauche keine erlaubniss.

**Comment by lemanschik** [comment]
Ich mach hier praktisch nur die nachträgliche documentation davon
