### ISSUE TITLE
What's the scope of "abort these steps"?

### ISSUE THREAD

**Issue by chaals** [w3c/web-share#266]
In various subsections of the algorithm that defines the implementation of the [`share` method](https://www.w3.org/TR/2022/PR-web-share-20221215/#share-method) there is the instruction

> abort these steps.

However, it is unclear whether the steps referred to are those in the "subroutine" (and in each case in this algorithm the instruction is within a "subroutine" conditionally entered) or those of the algorithm as a whole.

Perhaps "terminate the algorithm" or something similar would be clearer language?

**Comment by marcoscaceres** [comment]
Yeah, should probably switch to terminate this algorithm.

**Comment by hober** [comment]
Maybe an issue should be raised against [Infra](https://infra.spec.whatwg.org/) to define a phrase to use?

**Comment by chaals** [comment]
@hober done: https://github.com/whatwg/infra/issues/527

**Comment by marcoscaceres** [comment]
@chaals, sent https://github.com/w3c/web-share/pull/268 ... can you please take a look and approve for record keeping purposes. 

Thanks in advance!!!
