### ISSUE TITLE
Make Security Considerations an explicitly named section?

### ISSUE THREAD

**Issue by chaals** [w3c/web-share#267]
It's helpful, even in a short spec where the bulk of security considerations are described in a single place to have an explicit revision of them that can be found. Unlike with a very large spec, the task of doing that for yourself probably isn't beyond the average implementor, so this is merely an editorial suggestion.

**Comment by marcoscaceres** [comment]
We originally listed them but then baked them back into the algorithm at the request of the Sec folks. https://github.com/w3c/web-share/pull/245

If it’s ok, we’d like to keep it as is.

**Comment by chaals** [comment]
I'd prefer it were possible to find them in one go as well - I do like that they are mentioned directly in relevant places, I just want everything :). But I can live with it as is - as mentioned, the spec isn't massive so it's feasible to find them all on my own....
